meta_product_name: "Open Closet"
meta_title: "Open Closet - Rent clothes everywhere"
meta_description: "Find the perfect outfit for your party, your week-end espace or your next interview.
Don't let your clothes sleep in your closet !"
meta_image: "logo_ecriture_gris_og.png"
